[project]
authors = ["Ryan Oates <ryanoatsie@outlook.com>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "Add a short description here"
name = "my-google-cloud-magic-cli-sdk"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
gcloud = "*"
